CREATE TABLE IF NOT EXISTS user_entity(
      id UUID PRIMARY KEY,
      username VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario (
   id SERIAL PRIMARY KEY,
   nombre VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);